FROM node:22-alpine
WORKDIR /app
COPY package.json /app/package.json
COPY apps/web/package.json /app/apps/web/package.json
COPY packages/shared-schemas/package.json /app/packages/shared-schemas/package.json
RUN npm install
COPY . /app
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["npm", "run", "dev"]

